### ISSUE TITLE
no such table: background_image_backgroundimage

### ISSUE THREAD

**Issue by ni8mr** [arteria/django-background-image#1]
I have installed **django-background-image** and than installed **pillow**. When i navigate to the link -*_http://localhost:8080/admin/background_image/backgroundimage/add/ *_ and try to add an image, i am getting the following error -

```
no such table: background_image_backgroundimage
```

May be it is not an issue related to the development process of this app, but i couldn't find any place to discuss about this issue.

 If i need to create or edit something in models, than you should mention that to your *_Readme.MD *_ file.

**Comment by philippeowagner** [comment]
Yes, tables must be created first. 

Added a notice to the README in 30d2c80.
